# Generated by Django 3.1 on 2020-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='photo',
            field=models.ImageField(default=0, upload_to='photo/%y/%m/%d'),
        ),
    ]
